### ISSUE TITLE
Remove dependencies on influxdata/influxdb and influxdata/platform

### ISSUE THREAD

**Issue by vito** [influxdata/influxdb1-client#1]
Hi there, really glad to see a separate repo for this as importing from `influxdb` proper used to pull in a ton of other dependencies that we don't really need as a client consumer.

I noticed however that `points.go` still imports from `influxdata/influxdb` and `influxdata/platform` which pulls in a bunch of other stuff:

https://github.com/influxdata/influxdb1-client/blob/e237d47d0fc87c8ba2b7c98c349cdceca9c37e27/models/points.go#L18-L19

To be honest part of my reasoning for wanting to avoid all these dependencies is that there are a couple dependencies on `bzr` repositories (namely `gocheck`). These tend to be much slower and flakier to fetch. Ideally Go modules would just ignore them (as we have no need to pull in test dependencies), but at least right now it really throws a wrench into our builds.

Not sure if it's a priority to keep this repo fairly self-contained, but removing that dependency would help a lot. If not I'm OK with this issue just being closed.

Thanks!

**Comment by mark-rushakoff** [comment]
Hey @vito!

That was an accidental oversight. We'll get those dependencies removed soon.

**Comment by vito** [comment]
Hey @mark-rushakoff, long time no see! :slightly_smiling_face: 

Awesome, thanks!

**Comment by mark-rushakoff** [comment]
Fixed in f8cdb5d5f1752d3578a055342232883f45b7283d.

Cool to run into you on GitHub again, and cool to see you're still working on CF too.

**Comment by vito** [comment]
Kinda! Been working on [Concourse](https://github.com/concourse) for a while now which is technically CF R&D but is a bit of an island.

Good memories though! See ya around.

edit: and thanks!
