### ISSUE TITLE
Question: how to query data from InfluxDB in chunk

### ISSUE THREAD

**Issue by sasadangelo** [influxdata/influxdb1-client#44]
Hi all,

I have the following problem. I have an InfluxDB server where I have a go controller that fetches metrics remotely and store them into an InfluxDB. I need to create now a go forwarder program that reads these metrics from the N measurements (tables) and sends them to another server.

My problem is that I don't know which is the best approach.

I know this library support chunk responses but my problem is that during my query into a measurement:
select * from mymeasurement

1. other data can arrive
2. at each iteration I do not want to send the data already sent.

Hope someone can help here.

**Comment by sasadangelo** [comment]
Solved with an easier approach.

**Comment by shreyag-git** [comment]
I have a similar problem statement, can you please share the approach you chose?
